# Generated by Django 4.2 on 2023-04-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_credit_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='email',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
