# Generated by Django 4.2 on 2023-04-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_credit_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='image',
            field=models.ImageField(default='temp.jpg', upload_to=None),
        ),
    ]
