# Generated by Django 4.2 on 2023-04-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_credit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='image',
            field=models.ImageField(default='temp.jpeg', upload_to=None),
        ),
    ]
